COMMAND_TOPIC = "roborio/keyboard/command"  # Use this to send commands to the robot
CONFIRM_TOPIC = "roborio/keyboard/confirm"  # Robot sets this to its most recent command
DIRECTION = "direction"
SPEED = "speed"
STOP = "STOP"
FORWARD = "FORWARD"
BACKWARD = "BACKWARD"
LEFT = "LEFT"
RIGHT = "RIGHT"
